language: node_js
matrix:
  include:
  - env: TEST_TARGET=browser
    node_js: 10
  - env: TEST_TARGET=node
    node_js: 5
  - env: TEST_TARGET=node
    node_js: 6
  - env: TEST_TARGET=node
    node_js: 7
  - env: TEST_TARGET=node
    node_js: 8
  - env: TEST_TARGET=node
    node_js: 9
  - env: TEST_TARGET=node
    node_js: 10
script:
- npm run lint
- npm run dist
- npm run transpile
- npm test
deploy:
  provider: npm
  email: marius@transloadit.com
  api_key:
    secure: deLv8rCb1nN4vcFCSlPLVLcZJ20vLWNPaAA4PZAUXcQdUFX8mc++qDusS0o3LqdQVIugeOkSBTuKq8GQxOpMahj3U0WDe7Dy+t5xS/kPejr1H4m/VT1A5uRfBLGHgjuQzZH1L/RzAAca7Przx9fNe/1y1+RblDbbE7oOXQWiIUs=
  skip_cleanup: true
  on:
    tags: true
    repo: tus/tus-js-client
    node: 10
