language: node_js
matrix:
  include:
  - env: TEST_TARGET=browser
  - env: TEST_TARGET=node
    node_js: 4
  - env: TEST_TARGET=node
    node_js: 5
  - env: TEST_TARGET=node
    node_js: 6
script:
- npm install -g node-static
- static -p 8081 &
- npm run lint
- npm run dist
- npm test
deploy:
  provider: npm
  email: marius@accoplex.com
  api_key:
    secure: jyOlnZKkGmt1/3YH3Gs00zkOD7R0iXmHhtSsWCXrtlWXr8XqjH5DH6WRNOvr2JnI1NJO2Zz0e1EAjKNbUVfS/SWELlR9GX+yJr9QtgWce92zizL4Finp3VeGtZ8ZBBukbPogQW80Dvc8zb2FhpnxdW83lGlqGqyL7o7BT+0S7tQ=
  skip_cleanup: true
  on:
    tags: true
    repo: tus/tus-js-client
addons:
  sauce_connect:
    tunnel_domains: localhost
    no_ssl_bump_domains: www.google.com,www.gstatic.com,ssl.gstatic.com
